AWSTemplateFormatVersion: 2010-09-09
Description: |
  - Task Definition
  - Fargate Service
  - Execution Role
  - Task Role
Parameters:
  NetworkingStack:
    Type: String
    Default: OmgNet
  ClusterStack:
    Type: String
    Default: OmgCluster
  ContainerName:
    Type: String
    Default: 'backend-flask'
  ContainerPort:
    Type: String
    Default: 4567
  ServiceName:
    Type: String
    Default: 'backend-flask'
  some:
    Type: String
    Default: 4567
Resources:
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html
  FargateService:
    Type: AWS::ECS::Service
    Properties:
      Cluster:
        Fn::ImportValue:
          !Sub "${ClusterStack}ClusterName" 
      DeploymentController:
        Type: ECS
      DesiredCount: 1
      EnableECSManagedTags: true
      EnableExecuteCommand: true
      HealthCheckGracePeriodSeconds: 0
      LaunchType: FARGATE
      LoadBalancers:
        - TargetGroupArn: 
            Fn::ImportValue:
              !Sub "${AWS::ClusterStack}BackendTGArn"
          ContainerName: !Ref ContainerName
          ContainerPort: !Ref ContainerPort
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - Fn::ImportValue:
                !Sub "${AWS::ClusterStack}ALBSecGroupId"
          Subnets:
            - Fn::Split:
              - ","
              - Fn::ImportValue:
                  !Sub "${AWS::NetworkingStack}PublicSubnetIds"
      PlatformVersion: LATEST
      PropogateTags: SERVICE
      ServiceConnectConfiguration:
        Enabled: true
        NameSpace: omgchat
        Services: 
          - DiscoveryName: !Ref ServiceName
            PortName: !Ref ServiceName
            ClientAliases: 
              - Port: !Ref ContainerPort
      ServiceName: !Ref ServiceName
      TaskDefinition: !Ref TaskDefinition  
  TaskDefinition:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-taskdefinition.html
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Ref ServiceName
      ExecutionRoleArn: 
  
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html
  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
Outputs:
  ServiceName:
    Value: !GetAtt FargateService.Name
    Export:
      Name: !Sub