AWSTemplateFormatVersion: 2010-09-09
Description: |
  - Task Definition
  - Fargate Service
  - Execution Role
  - Task Role
Parameters:
  NetworkingStack:
    Type: String
    Default: OmgNet
  ClusterStack:
    Type: String
    Default: OmgCluster
