AWSTemplateFormatVersion: 2010-09-09
Description: |
  - AWS Fargate Cluster for omgchat App 
  - Application Load Balancer (ALB)
    * ipv4 only
    * internet facing
    * certificate attached from ACM
  - ALB Security Group
  - Backend Target Group
  - Frontend Target Group
  - HTTPS Listener
    * domain to frontend Target Group
    * api.domain to backend Target Group
  - HTTP Listener
    * redirect to HTTPS

Parameters:
  
Resources:
 FargateCluster:
  Type: 'AWS::ECS::Cluster' 
  Properties:
    ClusterName: !Sub "${AWS::StackName}Cluster"
    CapacityProviders:
      - FARGATE
    ClusterSettings:
      - Name: containerInsights
        Value: enabled
    Configuration:
      ExecuteCommandConfiguration:
        Logging: DEFAULT
    ServiceConnectDefaults:
      Namespace: omgchat
    ALB:
      Type: AWS::ElasticLoadBalancingV2::LoadBalancer
      Properties:
        Name: !Sub "${AWS::StackName}ALB"
        IpAddresType: ipv4 

      
  
Outputs: