AWSTemplateFormatVersion: 2010-09-09
Description: |
  - Create AWS Fargate Cluster for omgchat App 
  -
  -
  -
Parameters:
  
Metadata:
  
Mappings:
  
Conditions:
  
Resources:
 FargateCluster:
  Type: 'AWS::ECS::Cluster' 
  Properties:
    ClusterName: !Sub "${AWS::StackName}Cluster"
    CapacityProviders:
      - FARGATE
    ClusterSettings:
      - Name: containerInsights
        Value: enabled
    Configuration:
      ExecuteCommandConfiguration:
        Logging: DEFAULT
Transform:
  
Outputs: