FROM node:16.18 as build

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

COPY . ./

RUN npm run build
# stage 2
FROM nginx:1.16.0-alpine

WORKDIR /usr/share/nginx/html

RUN rm -rf ./*
 
COPY --from=build /app/build .

EXPOSE 80

ENTRYPOINT [ "nginx", "-g", "daemon off;" ]