---
AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template for creating a VPC with subnets, Internet Gateway, and Router Table

Parameters:
  VpcCidrBlock:
    Type: CommaDelimitedList
    Default: >
      10.0.0.0/16,
      172.31.0.0/16,
      192.168.0.0/20
  SubnetCidrBlocks:
    Type: CommaDelimitedList
    Default: > 
      10.0.0.0/24,
      10.0.1.0/24,
      10.0.2.0/24,
      10.0.3.0/24,
      10.0.4.0/24,
      10.0.5.0/24,
      172.31.0.0/24,
      172.31.1.0/24,
      172.31.2.0/24,
      172.31.3.0/24,
      172.31.4.0/24,
      172.31.5.0/24,
      192.168.0.0/24,
      192.168.1.0/24,
      192.168.2.0/24,
      192.168.3.0/24,
      192.168.4.0/24,
      192.168.5.0/24
  AZ:
    Type: List<AWS::EC2::AvailabilityZone::Name>
    Default: >
     eu-central-1a,
     eu-central-1b
  SubnetCidrBlocks:
    Type: AWS:EC2::Subnet
Resources:
  OmgchatVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}VPC"

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}IGW"

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref OmgchatVPC
      InternetGatewayId: !Ref InternetGateway

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref OmgchatVPC
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: eu-central-1a

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref OmgchatVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: eu-central-1b

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref OmgchatVPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: eu-central-1a

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref OmgchatVPC
      CidrBlock: 10.0.3.0/24
      AvailabilityZone: eu-central-1b

  PrivateSubnet3:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref OmgchatVPC
      CidrBlock: 10.0.4.0/24
      AvailabilityZone: eu-central-1a

  PrivateSubnet4:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref OmgchatVPC
      CidrBlock: 10.0.5.0/24
      AvailabilityZone: eu-central-1b

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref OmgchatVPC

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: VPCGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRouteTable

  PublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicRouteTable