AWSTemplateFormatVersion: 2010-09-09
Description: |
  Testing Setup ECS Cluster 
Resources:
  ECSCluster: # Logical Name 
    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterName: MyEmptyCluster   
      CapacityProviders: 
       - FARGATE

#Parameters:
